<a href="https://colab.research.google.com/github/francisco-gamez/learning_NumPy/blob/main/Leyendo_archivos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula 1 - Leyendo archivos CSV

## Importando archivos CSV

In [1]:
import pandas as pd

In [2]:
datos = pd.read_csv('/content/superstore_data.csv')
datos.head()

FileNotFoundError: [Errno 2] No such file or directory: '/content/superstore_data.csv'

In [ ]:
datos_punto_coma = pd.read_csv('/content/superstore_data_punto_coma.csv', sep=';')
datos_punto_coma.head()

In [ ]:
datos_primeras_lineas = pd.read_csv('/content/superstore_data.csv', nrows= 5)
datos_primeras_lineas

In [ ]:
datos_seleccion = pd.read_csv('/content/superstore_data.csv', usecols=['Id','Year_Birth','Income'])
datos_seleccion

In [ ]:
datos_seleccion = pd.read_csv('/content/superstore_data.csv', usecols=[0, 1, 4])
datos_seleccion

In [ ]:
datos_seleccion.to_csv('clientes_mercado.csv', index=False)

In [ ]:
clientes_mercado = pd.read_csv('/content/clientes_mercado.csv')
clientes_mercado

# Aula 2 - Leyendo archivos Excel

## Importando archivos Excel

In [ ]:
archivo = '/content/emisiones_CO2.xlsx'

In [ ]:
datos_co2 = pd.read_excel(archivo)
datos_co2.head()

In [ ]:
pd.ExcelFile(archivo).sheet_names

In [ ]:
percapita = pd.read_excel(archivo,sheet_name='emisiones_percapita')

In [ ]:
percapita.head()

In [ ]:
percapita.tail()

In [ ]:
percapita.sample(5)

In [ ]:
fuentes = pd.read_excel(archivo,sheet_name='fuentes')
fuentes.tail()

In [ ]:
intervalos = pd.read_excel(archivo,sheet_name='emisiones_C02',usecols= 'A:D')
intervalos

In [ ]:
intervalos_2 = pd.read_excel(archivo,sheet_name='emisiones_C02',usecols= 'A:D', nrows=10)
intervalos_2

## Escribiendo archivos de Excel

In [ ]:
intervalos.to_excel('co2_percapita.xlsx', index= False)

In [ ]:
pd.read_excel('co2_percapita.xlsx')

## Importando archivos google sheets

In [ ]:
sheet_id = '1FhVzXK7TzzHLc83bJmMkv3uU-1yXA0r0NpCQhpBzzwA'
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

In [ ]:
datos_co2_sheets = pd.read_csv(url)

In [ ]:
datos_co2_sheets

In [ ]:
sheet_id = '1FhVzXK7TzzHLc83bJmMkv3uU-1yXA0r0NpCQhpBzzwA'
sheet_name = 'emisones_percapita'
url_percapita = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'
percapita_sheets = pd.read_csv(url_percapita)
percapita_sheets

In [ ]:
sheet_id = '1FhVzXK7TzzHLc83bJmMkv3uU-1yXA0r0NpCQhpBzzwA'
sheet_name = 'fuentes'
url_fuentes = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'
fuentes_sheets = pd.read_csv(url_fuentes)
fuentes_sheets.head()

In [ ]:
fuentes_sheets.tail()

# Aula 3 - Leyendo archivos JSON

## Importación de archivos JSON (JavaScript Object Notation - Notación de objetos JavaScript)

In [ ]:
datos_pacientes = pd.read_json('/content/pacientes.json')
datos_pacientes

In [ ]:
datos_pacientes2 = pd.read_json('/content/pacientes_2.json')
datos_pacientes2

## Normalizando archivos JSON

In [ ]:
df_normalizado = pd.json_normalize(datos_pacientes2['Pacientes'])

In [ ]:
df_normalizado

## Escribiendo archivos JSON

In [ ]:
df_normalizado.to_json('historico_pacientes_norm.json')

In [ ]:
pd.read_json('historico_pacientes_norm.json')

# Aula 4 - Leyendo páginas en HTML e XML

## Importando páginas web

In [ ]:
datos_html = pd.read_html('peliculas_wikipedia.html')
datos_html

In [ ]:
type(datos_html)

In [ ]:
len(datos_html)

In [ ]:
top_peliculas = datos_html[1]
top_peliculas

## Escribiendo archivos HTML

In [ ]:
top_peliculas.to_html('top_peliculas.html',index = False)

In [ ]:
pd.read_html('top_peliculas.html')

In [ ]:
top_peliculas.to_csv('top_peliculas_1998.csv', index=False)

In [ ]:
datos = pd.read_csv('top_peliculas_1998.csv')
datos.head()

## Leyendo/escribiendo archivos XML

In [ ]:
datos_imbd = pd.read_xml('/content/imdb_top_1000.xml')
datos_imbd.head(3)

In [ ]:
datos_imbd.to_xml('peliculas_imdb.xml')

In [ ]:
pd.read_xml('peliculas_imdb.xml')

# Aula 5 - Leyendo banco de datos

## Creando un banco de datos local

In [3]:
import pandas as pd

In [4]:
import sqlalchemy

In [5]:
from sqlalchemy import create_engine, MetaData, Table, inspect, text

In [6]:
engine = create_engine('sqlite:///:memory:')

## Escribiendo en un banco de datos

In [7]:
archivo = 'clientes_banco.csv'

In [8]:
datos = pd.read_csv(archivo)

In [9]:
datos.head()

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio

In [10]:
datos.to_sql('clientes', engine, index=False)

438463

In [11]:
inspector = inspect(engine)

In [12]:
print(inspector.get_table_names())

['clientes']

## Leyendo una consulta SQL

In [13]:
query = 'SELECT * FROM clientes WHERE categoria_de_renta = "Empleado"'

In [19]:
empleados = pd.read_sql(sql=text(query),con = engine.connect())

In [20]:
type(empleados)

pandas.core.frame.DataFrame

In [15]:
empleados

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008815,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
4,5112956,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
226054,6837905,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226055,6837906,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226056,6839936,34,Nivel intermedio,Casado,3,Empleado,Construcción Civil,5,135000.0,1,Casa/Departamento propio
226057,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
226058,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [16]:
empleados.to_sql('emplados',con = engine.connect(), index=False)

226059

In [17]:
pd.read_sql_table('emplados',con = engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008815,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
4,5112956,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
226054,6837905,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226055,6837906,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226056,6839936,34,Nivel intermedio,Casado,3,Empleado,Construcción Civil,5,135000.0,1,Casa/Departamento propio
226057,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
226058,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [18]:
pd.read_sql_table('emplados',con = engine.connect(),columns=['ID_Cliente'	,'Grado_estudio','Rendimiento_anual'])

        ID_Cliente     Grado_estudio  Rendimiento_anual
0          5008804    Nivel superior           427500.0
1          5008805    Nivel superior           427500.0
2          5008806  Nivel intermedio           112500.0
3          5008815    Nivel superior           270000.0
4          5112956    Nivel superior           270000.0
...            ...               ...                ...
226054     6837905  Nivel intermedio           355050.0
226055     6837906  Nivel intermedio           355050.0
226056     6839936  Nivel intermedio           135000.0
226057     6840222  Nivel intermedio           103500.0
226058     6842885  Nivel intermedio           121500.0

[226059 rows x 3 columns]

In [21]:
query = 'SELECT * FROM clientes'

In [22]:
pd.read_sql(sql=text(query),con=engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,135000.0,0,Casa/Departamento propio
438459,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
438460,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438461,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438462,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [23]:
#Borrando registros
from sqlalchemy.exc import SQLAlchemyError
query = "DELETE FROM clientes WHERE ID_Cliente = 5008804"
try:
  r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print (e)
else:
  print('#Registros borrados: ', r_set.rowcount)

#Registros borrados:  1

In [24]:
pd.read_sql_table('clientes', con=engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
2,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
3,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008810,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438457,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,135000.0,0,Casa/Departamento propio
438458,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
438459,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438460,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438461,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [26]:
#Actualizando registros
query = "UPDATE clientes SET Grado_estudio = 'Nivel superior' WHERE ID_Cliente = 5008808"
try:
  r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print (e)
else:
  print('#Registros actualizados: ', r_set.rowcount)

#Registros actualizados:  1

In [27]:
pd.read_sql_table('clientes', con=engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
2,5008808,52,Nivel superior,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
3,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008810,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438457,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,135000.0,0,Casa/Departamento propio
438458,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
438459,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438460,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438461,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [28]:
inspector = inspect(engine)
print(inspector.get_table_names())

['clientes', 'emplados']